package com.aioshell.app.core.ui.theme

import androidx.compose.ui.graphics.Color

// ---- 深色「深渊翡翠」(Abyssal Teal) ----
internal val DarkPrimary = Color(0xFF7CD9CF)
internal val OnDarkPrimary = Color(0xFF003731)
internal val DarkPrimaryContainer = Color(0xFF005049)
internal val OnDarkPrimaryContainer = Color(0xFF9DF4EA)
internal val DarkSecondary = Color(0xFFB1CCC8)
internal val OnDarkSecondary = Color(0xFF1B3531)
internal val DarkSecondaryContainer = Color(0xFF31504B)
internal val OnDarkSecondaryContainer = Color(0xFFCDE9E4)
internal val DarkTertiary = Color(0xFFA3CADF)
internal val OnDarkTertiary = Color(0xFF073346)
internal val DarkTertiaryContainer = Color(0xFF274B5F)
internal val OnDarkTertiaryContainer = Color(0xFFBFE7FA)
internal val DarkError = Color(0xFFFFB4AB)
internal val OnDarkError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val OnDarkErrorContainer = Color(0xFFFFDAD6)
internal val DarkBackground = Color(0xFF101413)
internal val OnDarkBackground = Color(0xFFDDE4E2)
internal val DarkSurface = Color(0xFF101413)
internal val OnDarkSurface = Color(0xFFDDE4E2)
internal val DarkSurfaceVariant = Color(0xFF3F4846)
internal val OnDarkSurfaceVariant = Color(0xFFBFC8C6)
internal val DarkSurfaceDim = Color(0xFF101413)
internal val DarkSurfaceBright = Color(0xFF363D3B)
internal val DarkOutline = Color(0xFF89918F)
internal val DarkOutlineVariant = Color(0xFF3F4846)

// ---- 亮色「海玻璃」(Sea Glass) ----
internal val LightPrimary = Color(0xFF0B6B60)
internal val OnLightPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFF98F1E5)
internal val OnLightPrimaryContainer = Color(0xFF00201B)
internal val LightSecondary = Color(0xFF4A635F)
internal val OnLightSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFCCE8E3)
internal val OnLightSecondaryContainer = Color(0xFF06201C)
internal val LightTertiary = Color(0xFF3E6375)
internal val OnLightTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFC1E8FC)
internal val OnLightTertiaryContainer = Color(0xFF001F2D)
internal val LightError = Color(0xFFBA1A1A)
internal val OnLightError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val OnLightErrorContainer = Color(0xFF410002)
internal val LightBackground = Color(0xFFFAFDFB)
internal val OnLightBackground = Color(0xFF191C1B)
internal val LightSurface = Color(0xFFFAFDFB)
internal val OnLightSurface = Color(0xFF191C1B)
internal val LightSurfaceVariant = Color(0xFFDBE5E2)
internal val OnLightSurfaceVariant = Color(0xFF3F4947)
internal val LightSurfaceDim = Color(0xFFDAE0DE)
internal val LightSurfaceBright = Color(0xFFFAFDFB)
internal val LightOutline = Color(0xFF6F7977)
internal val LightOutlineVariant = Color(0xFFBFC9C6)

// 新增：耳明文暗两级表面容器（供 M3 Scrim / 悬浮层使用）
internal val DarkSurfaceContainer = Color(0xFF1C2221)
internal val DarkSurfaceContainerHigh = Color(0xFF262C2B)
internal val LightSurfaceContainer = Color(0xFFEEF4F2)
internal val LightSurfaceContainerHigh = Color(0xFFE8EEEC)